### ISSUE TITLE
Hello, Sorry to interrupt!

### ISSUE THREAD

**Issue by Erald-Whitey** [Morb0/nestjs-airgram#1]
Sorry, hope you are doing great but im kindda confused how can i really use this library because we have a react frontend and i implemented this in my nestjs backend. Hell of a work btw ! KUDOS!

**Comment by Morb0** [comment]
Give details. You can't install the library?
Have you encountered errors or don't know how to implement something?

**Comment by Erald-Whitey** [comment]
Hello, i am really greatful that i have an answer that quick, in fact i install library and everything else but i am new at backend and i would like to know i need to create a controller for each of the methods or how does it work to send data to frontend ? Hope you can help me, thanks again!

**Comment by Morb0** [comment]
If you want to know how to communicate with the frontend, maybe you should read the NestJS docs about [controllers ](https://docs.nestjs.com/controllers) first.
If you want to know how to pass data from this library to frontend, you'll probably need [WebSocket ](https://docs.nestjs.com/websockets/gateways) or [SSE](https://docs.nestjs.com/techniques/server-sent-events).

**Comment by Erald-Whitey** [comment]
Yeah, i know about controllers, i see that websockets will help me this time, it was really helpful by you really thank you!
